disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - opening_brace
  - variable_name
  - function_body_length
  - statement_position
  - type_name
  - force_try
  - comma
  - trailing_semicolon
  - control_statement
  - file_length
  - function_parameter_count
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  -  
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Submodules
line_length:
  - 200
  - 300
type_body_length:
  - 300 # warning
  - 800 # error
function_body_length:
  - 60
  - 120